<?php


return [
    'CST6CDT' => 'America/Chicago',
    'Cuba' => 'America/Havana',
    'Egypt' => 'Africa/Cairo',
    'Eire' => 'Europe/Dublin',
    'EST5EDT' => 'America/New_York',
    'Factory' => 'UTC',
    'GB-Eire' => 'Europe/London',
    'GMT0' => 'UTC',
    'Greenwich' => 'UTC',
    'Hongkong' => 'Asia/Hong_Kong',
    'Iceland' => 'Atlantic/Reykjavik',
    'Iran' => 'Asia/Tehran',
    'Israel' => 'Asia/Jerusalem',
    'Jamaica' => 'America/Jamaica',
    'Japan' => 'Asia/Tokyo',
    'Kwajalein' => 'Pacific/Kwajalein',
    'Libya' => 'Africa/Tripoli',
    'MST7MDT' => 'America/Denver',
    'Navajo' => 'America/Denver',
    'NZ-CHAT' => 'Pacific/Chatham',
    'Poland' => 'Europe/Warsaw',
    'Portugal' => 'Europe/Lisbon',
    'PST8PDT' => 'America/Los_Angeles',
    'Singapore' => 'Asia/Singapore',
    'Turkey' => 'Europe/Istanbul',
    'Universal' => 'UTC',
    'W-SU' => 'Europe/Moscow',
    'Zulu' => 'UTC',
];
